name: 'LintAI Validation'
description: 'Validates LLM outputs using configurable assertions with confidence scoring'
author: 'Arush Kali'

inputs:
  prompt:
    description: 'The original prompt sent to the LLM'
    required: true
  output:
    description: 'The LLM output to validate'
    required: true
  assertions-config:
    description: 'Path to assertions configuration file (JSON/YAML)'
    required: true
  pass-threshold:
    description: 'Minimum score threshold for passing (0-100)'
    required: false
    default: '70'
  fail-on-warning:
    description: 'Fail validation if there are warnings'
    required: false
    default: 'false'

outputs:
  passed:
    description: 'Whether validation passed (true/false)'
  score:
    description: 'Validation confidence score (0-100)'
  failed-assertions:
    description: 'Number of failed assertions'
  warnings-count:
    description: 'Number of warnings'

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: 'check-circle'
  color: 'green'

